version: '3'
services:
  vue_client:
    build: .
    command: yarn serve
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - pdf-gen-service

networks:
  pdf-gen-service: