version: '3'
services:
  pdf_builder:
    build: .
    user: '1000'
    command: yarn start
    ports:
      - '3520:3520'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_PORT: 3520
      PDF_DIR: './pdfs'
    network_mode: 'host'

networks:
  default:
    external:
      name: localdev